LoVisto/LoVisto/LoVisto/urls.py
from django.urls import path, include
from .import views

urlpatterns = [
    path('',views.index),
    path('usuario/<str:llave>', views.pagina_usuario),
    path('aportaciones', views.pagina_aportaciones),
    path('info', views.pagina_info),
    path('<str:llave>', views.pagina_recurso)
]

LoVisto/LoVisto/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login
from django.contrib.auth.views import LogoutView as logout


urlpatterns = [
    path('LoVisto/', include('LoVisto.urls')),
    path('admin/', admin.site.urls),
    path('login/', login.as_view()),
    path('logout/', logout.as_view()),
]

LoVisto/LoVisto/LoVisto/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone

# Create your models here.

class Topic(models.Model):
    TOPICS = [('AE','Aemet'), ('WK','Wikipedia'), ('YU','Youtube'), ('RE','Reddit'),('OT','Other')]
    topic = models.CharField(max_length=2, choices=TOPICS)
    def __str__(self):
       return str(self.id) + ": " + self.topic


class Contenido(models.Model):
    usuario = models.TextField()
    titulo_noticia = models.CharField(max_length=128) #clave
    url_noticia = models.TextField() #valor
    Num_comentarios = models.IntegerField()
    votos_positivos = models.IntegerField()
    votos_negativos = models.IntegerField()
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id) + ": " + self.titulo_noticia



class Comentario(models.Model):
    usuario = models.TextField()
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    descripcion = models.TextField()
    url = models.TextField(default="No url")
    titulo = models.CharField(max_length=64, default="No title")
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id) + ": " + self.usuario

class Voto(models.Model):
    usuario = models.TextField()
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    valor = models.TextField(default="No valor")

    def __str__(self):
        return str(self.id) + ": " + self.usuario

LoVisto/LoVisto/LoVisto/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from . import models
from django.utils import timezone
from django.http import HttpResponse
from bs4 import BeautifulSoup
import requests
import requests_html
from urllib.request import urlopen
from django.http import JsonResponse

from .models import Contenido, Comentario, Voto


@csrf_exempt
def pagina_recurso(request, llave):
    modo = 0
    if request.method == "PUT":
        url_noticia = request.body.decode('utf-8')
    if request.method == "POST":
        action = request.POST['action']
        if action == "Editar contenido":
            try:
                contenido = Contenido.objects.get(titulo_noticia=llave)
                contenido.url_noticia = request.POST['url_noticia']
                contenido.save()
            except Contenido.DoesNotExist:
                contenido = Contenido(titulo_noticia=llave, url_noticia=request.POST['url_noticia'])
                contenido.save()

        elif action == "Enviar contenido":
            titulo_noticia = llave
            try:
                contenido = Contenido.objects.get(titulo_noticia=titulo_noticia)
                contenido.delete()
            except Contenido.DoesNotExist:
                pass
            contenido = Contenido(titulo_noticia=titulo_noticia, url_noticia=request.POST['url_noticia'],
                                  usuario=request.user.username,
                                  votos_positivos=0, votos_negativos=0, Num_comentarios=0, fecha=timezone.now())
            contenido.save()

        elif action == "LIKE":
            contenido = Contenido.objects.get(titulo_noticia=llave)
            contenido.votos_positivos += 1
            contenido.save()
            voto = Voto(contenido=Contenido.objects.get(titulo_noticia=llave), usuario=request.user.username,
                        valor="like")
            voto.save()

        elif action == "DISLIKE":
            contenido = Contenido.objects.get(titulo_noticia=llave)
            contenido.votos_negativos = contenido.votos_negativos + 1
            contenido.save()
            voto = Voto(contenido=Contenido.objects.get(titulo_noticia=llave), usuario=request.user.username,
                        valor="dislike")
            voto.save()

        elif action == "Inicio de sesion":
            return redirect('/login')

        elif action == "Cerrar sesion":
            logout(request)
            return redirect('/LoVisto')

        elif action == "Borrar contenido":
            try:
                contenido = Contenido.objects.get(titulo_noticia=llave)
                contenido.delete()
                return redirect('/LoVisto')
            except Contenido.DoesNotExist:
                contenido = Contenido.objects.get(titulo_noticia=llave, url_noticia=url_noticia)
                contenido.save()

        elif action == "Pagina principal":
            return redirect('/LoVisto')

        elif action == "Página usuario":
            return redirect('usuario/<request.user.username>')

        elif action == "Resumen aportaciones":
            return redirect('/LoVisto/aportaciones')

        elif action == "Info":
            return redirect('/LoVisto/info')
        elif action == "Oscuro":
            modo = 1
        elif action == "Claro":
            modo = 0
        elif action == "Borrar votacion":
            contenido = Contenido.objects.get(titulo_noticia=llave)
            voto = Voto.objects.get(contenido=Contenido.objects.get(titulo_noticia=llave),
                                    usuario=request.user.username)
            if voto.valor == "like":
                contenido.votos_positivos -= 1
            elif voto.valor == "dislike":
                contenido.votos_negativos -= 1
            contenido.save()
            voto.delete()

        elif action == "Enviar comentario":
            contenido = Contenido.objects.get(titulo_noticia=llave)
            contenido.Num_comentarios += 1
            coment = Comentario(contenido=contenido, titulo=request.POST['titulo'],
                                descripcion=request.POST['descripcion'],
                                url=request.POST['url'], fecha=timezone.now(), usuario=request.user.username)
            coment.save()
            contenido.save()
    try:
        Contenido.objects.get(titulo_noticia=llave)
    except Contenido.DoesNotExist:
        if request.GET.get("format") == "xml/":
            xml = loader.get_template('LoVisto/xml.html')
            contexto = {'Claves': Contenido.objects.all()}
            return HttpResponse(xml.render(contexto, request))
        if request.GET.get("format") == "json/":
           contenido = Contenido.objects.filter().values()
           return JsonResponse({"Contenido": list(contenido)})

        lista_contenidos = Contenido.objects.all()
        lista_contenidos_slice2 = lista_contenidos[0:3]
        contexto = {'lista_contenidos_slice2': lista_contenidos_slice2, 'modo': modo}
        return render(request, 'LoVisto/pagina_contenido_no_encontrado.html', contexto)

    lista_contenidos = Contenido.objects.all()
    lista_contenidos_slice2 = lista_contenidos[0:3]
    lista_comentarios = (Comentario.objects.all())
    lista_votos = Voto.objects.all()
    llave = llave

    contenido = Contenido.objects.get(titulo_noticia=llave)
    url = contenido.url_noticia
    headers = {'User-Agent': 'Mozilla/5.0'}
    try:
        html_page = requests.get(url, headers=headers)
        Bsoup = BeautifulSoup(html_page.text, 'html.parser')
        if "www.aemet.es" in url:
            try:
                title = Bsoup.find("title").text
                temperatura = Bsoup.find("div", class_="no_wrap").text
                fecha = Bsoup.find("th", class_="borde_izq_dcha_fecha").text
                maxmin = Bsoup.find("td", class_="alinear_texto_centro no_wrap comunes").text
                precipitacion = Bsoup.find("td", class_="nocomunes").text
                viento = Bsoup.find('div', class_="texto_viento").text

                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'title': title,
                    'temperatura': temperatura,
                    'fecha': fecha,
                    'maxmin': maxmin,
                    'precipitacion': precipitacion,
                    'viento': viento,
                    'modo': modo
                }
                return render(request, 'LoVisto/pagina_AEMET.html', contexto)
            except AttributeError:
                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'modo': modo
                }
            return render(request, 'LoVisto/pagina_recurso_error.html', contexto)

        elif "es.wikipedia.org" in url:
            try:
                title = Bsoup.find(id="firstHeading").text
                text = Bsoup.find(id="bodyContent").text
                txt = text[0:400]
                images = Bsoup.findAll('img')
                imagen = ((images[0])['src'])

                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'title': title,
                    'txt': txt,
                    'imagen': imagen,
                    'modo': modo
                }
                return render(request, 'LoVisto/pagina_wiki.html', contexto)
            except AttributeError:
                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'modo': modo}
            return render(request, 'LoVisto/pagina_recurso_error.html', contexto)

        elif "www.reddit.com" in url:
            try:
                text = Bsoup.find("p", class_="_1qeIAgB0cPwnLhDF9XSiJM").text
                title = Bsoup.find("title").text
                images = Bsoup.findAll('img')
                imagen = ((images[0])['src'])

                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'text': text,
                    'title': title,
                    'imagen': imagen,
                    'modo': modo}
                return render(request, 'LoVisto/pagina_reddit.html', contexto)
            except AttributeError:
                contexto = {
                    'contenido': contenido,
                    'lista_contenidos_slice2': lista_contenidos_slice2,
                    'lista_comentaarios': lista_comentarios,
                    'lista_votos': lista_votos,
                    'modo': modo
                }
            return render(request, 'LoVisto/pagina_recurso_error.html', contexto)


        elif "www.marca.com" in url:
            try:
                title = Bsoup.find(class_="ue-c-article__headline js-headline js-headlineb").text
                text = Bsoup.find("p", class_="ue-c-article__standfirst").text
                images = Bsoup.findAll('img')
                imagen = ((images[1])['src'])
                contexto = {

LoVisto/LoVisto/templates/LoVisto/index.html
{% extends 'LoVisto/schema.html' %}
{% block cuerpo %}
    {% if lista_contenidos_slice %}
    <h1>
        <p> Página principal de LoVisto </p>
        <p> Aquí podrás ver las publicaciones de otras personas, valorarlas, comentarlas y tambien subir tus propias publicaciones!! </p>
    </h1>
        {% for contenido in lista_contenidos_slice %}
<br><br>
            <table style="width:au" align="rigth">
                <style>a { color: red }</style>
                <th><a href="/LoVisto/{{ contenido.titulo_noticia }}">{{ contenido.titulo_noticia }}</a></th>
                <tr>
                    <td>Url de la noticia: </td>
                <th><a href="{{ contenido.url_noticia }}">{{ contenido.url_noticia }}</a></th>
                </tr>
                <tr>
                    <td>Votos positivos: </td>
                    <td>{{ contenido.votos_positivos }}</td>
                </tr>
                <tr>
                    <td>Votos negativos: </td>
                    <td>{{ contenido.votos_negativos }}</td>
                </tr>
                <tr>
                    <td>Fecha de publicación: </td>
                    <td>{{ contenido.fecha }}</td>
                </tr>
                <tr>
                    <td>Publicado por: </td>
                    <td>{{ contenido.usuario }}</td>
                </tr>
                <tr>
                    <td>Número de comentarios: </td>
                    <td>{{ contenido.Num_comentarios }}</td>
                </tr>
            </table>
        {% endfor %}
    {% else %}
        <p> No tenemos contenidos que mostrar </p>
    {% endif %}

{% endblock %}
{% block lateral %}
    {% if request.user.is_authenticated %}
        <br>
        <p> Añade nuevo contenido <p>
        <form action="" method ="POST">
             {% csrf_token %}
            <table style="width:auto" align="left">
               <tr>
                   <td> Título noticia: </td>
                   <td><input type="text" name="titulo_noticia" ></td>
               </tr>
                <tr>
                     <td> Url noticia: </td>
                     <td><input type="text" name="url_noticia"></td>
                </tr>
            </table>
    <input class="boton_personalizado" type="submit" name="action" value="Añadir contenido">
        </form>

    {% else %}
    <p>Tienes que estar autenticado para poder subir contenidos</p>
    {% endif %}

        {% if request.user.is_authenticated %}
            {% if lista_contenidos %}
            <br><br>
            Contenido del usuario
                {% for contenido in lista_contenidos %}
            <br>
                    {% ifequal contenido.usuario request.user.username %}
                <th><a href="{{ contenido.url_noticia }}">{{ contenido.titulo_noticia }}</a></th>
                    {% endifequal %}
                {% endfor %}
            <br>
            {% endif %}
        {% endif %}
        <br><br><br>

<p><a href="https://www.urjc.es/">Pagina URJC</a></p>
            <iframe src="https://www.urjc.es/" height="400" width="65%" name="demo">
             <p>Necesita iframes para poder observar la previsualización</p>
            </iframe>
{% endblock %}

LoVisto/LoVisto/templates/LoVisto/pagina_AEMET.html
{% extends 'LoVisto/pagina_recurso.html' %}
{%block aportacion%}
<div class="aemet">
<p>{{title}} </p>
<ul>
    <li>Dia: {{fecha}}</li>
    <li>Temperatura 12-18h: {{temp}}</li>
    <li>Temperatura máxima y mínima (°C): {{maxmin}}</li>
    <li>Probabilidad de precipitación: {{precipitacion}}</li>
    <li>Dirección viento: {{viento}}</li>
</ul>
<p>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.
<br>
    <a href={{contenido.url_noticia}}>Página de AEMET </a></p>
</div>
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_aportaciones.html
{% extends 'LoVisto/schema.html' %}
{% block cuerpo %}
    {% if lista_contenidos %}
    <h1>
        Aquí podrás ver la lista de las aportaciones
        <br>ordenadas de más recientes a más antiguas
    </h1>
    <table style="width:auto" align="center">
           {% for contenido in lista_contenidos %}
            <tr>
               <td>
                   <style>a { color: red } </style>
                   <a href="{{ contenido.titulo_noticia }}">{{ contenido.titulo_noticia }}</a>
               </td>
            </tr>
        {% endfor %}
   </table>
    {% else %}
        <p>No existen aportaciones para mostrar</p>
    {% endif %}
{% endblock %}
{% block lateral %}
<br>
<p><a href="https://www.urjc.es/">Pagina URJC</a></p>
            <iframe src="https://www.urjc.es/" height="400" width="65%" name="demo">
             <p>Necesita iframes para poder observar la previsualización</p>
            </iframe>
{% endblock %}

LoVisto/LoVisto/templates/LoVisto/pagina_contenido_no_encontrado.html
{% extends 'LoVisto/schema.html' %}
{% block cuerpo %}
    {% if request.user.is_authenticated %}
            El contenido no existe, pero lo puedes añadir si lo deseas
        <table style="width:auto" align="center">
            <form action="" method ="POST">
                {% csrf_token %}
               <tr>
                    <td><br>Url noticia: </td>
                     <td><input type="text" name="url_noticia"></td>
               </tr>
                <tr>
                     <td><br/><input class="boton_personalizado" type="submit" name="action" value="Enviar contenido"></td>
                </tr>
            </form>
         </table>
    {% else %}
         <p>Tienes que estar autenticado para poder subir comentarios</p>
    {%endif%}
{%endblock%}
{%block lateral%}
<form action="http://localhost:1234/LoVisto/" method ="POST">
            {% csrf_token %}
        <br/><input class="boton_personalizado" type="submit" name="action" value="Volver a página principal">
    <style>a { color: red }</style>

    </form>
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_larazon.html
{% extends 'LoVisto/pagina_recurso.html' %}
{%block aportacion%}
<div class="larazon">
    <p>Título: {{title}}</p>
    <p>Texto: {{text}}</p>
<img src={{imagen}} align="right" width="300">
<p>© LaRazon
<br>
    <a href={{contenido.url_noticia}}>Página de la Razón</a>
</div>
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_marca.html
{% extends 'LoVisto/pagina_recurso.html' %}
{% block aportacion %}
<div class="marca">
    <p>Título: {{title}}</p>
    <p>Texto: {{text}}</p>
<img src={{imagen}} align="right" width="350">
<p>© Marca
<br>
    <a href={{contenido.url_noticia}}>Página de Marca</a>
</div>
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_recurso.html
{% extends 'LoVisto/schema.html' %}
{% block cuerpo %}
<tr>
    <td>
        <table style="width:au" align="center">
            <style>a{ color: red }</style>
            <th><a href="{{ contenido.titulo_noticia }}"> {{ contenido.titulo_noticia }} </a></th>
            <tr>
                <td> Url de la noticia: </td>
            <th><a href="{{ contenido.url_noticia }}"> {{ contenido.url_noticia }} </a></th>
            </tr>
            <tr>
                <td> Votos positivos: </td>
                <td>{{ contenido.votos_positivos }}</td>
            </tr>
            <tr>
                <td> Votos negativos: </td>
                <td>{{ contenido.votos_negativos }}</td>
            </tr>
            <tr>
                <td> Fecha de publicación: </td>
                <td>{{ contenido.fecha }}</td>
            </tr>
            <tr>
                <td> Número de comentarios: </td>
                <td>{{ contenido.Num_comentarios }}</td>
            </tr>
        </table>
    </td>
</tr>
     {% if request.user.is_authenticated %}
        {% if contenido.voto_set.all %}
            {% for voto in contenido.voto_set.all %}
                {% ifequal voto.usuario request.user.username %}
                    <br> Usted votó {{ voto.valor }}
                        <form action="" method ="POST">
                            {% csrf_token %}
                            <td><input class="boton_personalizado" type="submit" name="action" value="Borrar votacion"></td>
                        </form>
                {% else %}
                <br><br>
                    <table style="width:auto" align="center">
                        <form action="" method ="POST">
                            {% csrf_token %}
                            <input class="boton_personalizado" type="submit" name="action" value="LIKE">
                        </form>

                        <form action="" method ="POST">
                            {% csrf_token %}
                            <input class="boton_personalizado" type="submit" name="action" value="DISLIKE">
                        </form>
                    </table>
                <br><br><br>
                {% endifequal %}
            {% endfor %}
        {% else %}
        <br>
        <table style="width:auto" align="center">
            <form action="" method ="POST">
                {% csrf_token %}
                <td><input class="boton_personalizado" type="submit" name="action" value="LIKE"></td>
            </form>
            <form action="" method ="POST">
                {% csrf_token %}
                <td><input class="boton_personalizado" type="submit" name="action" value="DISLIKE"></td>
            </form>
        </table>

<br><br>
        {% endif %}
    {% endif %}

{% block aportacion %}
{% endblock %}
<br><br>
    <p> Comentarios </p>
        {% for comentario in contenido.comentario_set.all%}
            <br>
            <table style="width:auto" align="center">
                <tr>
                    <td><b> Titulo: </b></td>
                    <td>{{ comentario.titulo }}</td>
                </tr>
                <tr>
                    <td><b>Descripción:</b></td>
                    <td> {{ comentario.descripcion }}</td>
                </tr>
                {% if comentario.url %}
                <tr>
                    <td><b>Imagen:</b></td>
                    <td><img src={{comentario.url}} align="center" width="300"></td>
                </tr>
                {% endif %}
                <tr>
                    <td><b>Usuario:</b></td>
                    <td> {{ comentario.usuario }}</td>
                </tr>
                <tr>
                    <td><b>Fecha:</b></td>
                    <td>{{ comentario.fecha }}</td>
                </tr>
            </table>
        {% endfor %}
 <br><br>
    <p> Votos </p>
        {% for voto in contenido.voto_set.all%}
            <br>
            <table style="width:auto" align="center">
                <tr>
                    <td><b> Usuario: </b></td>
                    <td>{{ voto.usuario }}</td>
                </tr>
                <tr>
                    <td><b> Valor: </b></td>
                    <td> {{ voto.valor }}</td>
                </tr>
            </table>
        {% endfor %}
    <br>

{% endblock %}
{% block lateral %}
{% if request.user.is_authenticated %}
    <p> Introduce nuevo comentario </p>
    <form action="" method ="POST">
        <table style="width:auto" align="center">
            {% csrf_token %}
            <tr>
                <td> Título: </td>
                <td> <input type="text" name="titulo"></td>
            </tr>
            <tr>
                <td> <br> Descripción: </td>
                <td> <input type="text" name="descripcion"></td>
            </tr>
            <tr>
                <td> <br> URL imagen: </td>
                <td> <input type="text" name="url"></td>
            </tr>
        </table>
        <br/><input class="boton_personalizado"  type="submit" name="action" value="Enviar comentario">
    </form>
{% else %}
    <p>Tienes que estar autenticado para poder subir comentarios</p>
{% endif %}
<br>
    {% ifequal  request.user.username  contenido.usuario %}
     <p> Edita el contenido </p>
        <form action="" method ="POST">
            <table style="width:auto" align="center">
                {% csrf_token %}
                <tr>
                    <td> Nueva url: </td>
                    <td><input type="text" name="url_noticia"></td>
                </tr>
            </table>
            <br> <br>
            <input class="boton_personalizado" type="submit" name="action" value="Editar contenido">
        </form>
<br>
         <p> Borra el contenido </p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado" type="submit" name="action" value="Borrar contenido">
        </form>
        {%else%}
            <br><br><p> Solo {{ contenido.usuario }} puede editar esta publicacion </p>
        {%endifequal%}
    <br><br>
     <p> Previsualizacion de <a href={{contenido.url_noticia}}> Pagina recurso </a></p>
   <iframe src="{{contenido.url_noticia}}" height="400" width="65%" name="demo">
      <p> Su navegador no es compatible con iframes </p>
    </iframe>
    <br><br>
<p><a href="https://www.urjc.es/">Pagina URJC</a></p>
            <iframe src="https://www.urjc.es/" height="400" width="65%" name="demo">
             <p>Necesita iframes para poder observar la previsualización</p>
            </iframe>
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_recurso_error.html
{% extends 'LoVisto/pagina_recurso.html' %}
{%block aportacion%}
No podemos extraer más información de esta página
{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_recurso_no_rec.html
{% extends 'LoVisto/pagina_recurso.html' %}

{%block aportacion%}
<div class="og">
  <p>Información extendida no disponible, recurso no reconocido</p>
  <p>Título:{{title}}</p>
  <img src={{imagen}} align="right" width="300">
</div>
  <a href={{contenido.url_noticia}}></a>

{%endblock%}

LoVisto/LoVisto/templates/LoVisto/pagina_reddit.html
{% extends 'LoVisto/pagina_recurso.html' %}
{% block aportacion %}
<div class="reddit">
<p> Nota Reddit: {{title}} </p>
    <img src="{{imagen}}" align="right" width="350">
<p> Texto: {{text}} </p>
<p><a href="https://www.reddit.com/r/django/comments/n842st">Publicado en [subreddit]</a></p>
</div>
<p>© Reddit
{% endblock %}

LoVisto/LoVisto/templates/LoVisto/pagina_usuario.html
{% extends 'LoVisto/schema.html' %}
{% block cuerpo %}
Bienvenido a tu página, {{ request.user.username }}
<br>Aquí podrás ver tus publicaciones, comentarios y votos
{%if lista_contenidos%}
<br>
<br>
<H3 align="center">Tus publicaciones </H3>
    {% for contenido in lista_contenidos %}
        {% ifequal contenido.usuario request.user.username %}
            <br>
                <table style="width:au" align="center">
                    <style>a { color: red }</style>
                        <th>
                            <a href="/LoVisto/{{ contenido.titulo_noticia }}">{{ contenido.titulo_noticia }}</a>
                        </th>
                    <tr>
                        <td>Url de la noticia:</td>
                         <th>
                             <a href="{{ contenido.url_noticia }}">{{ contenido.url_noticia }}</a>
                         </th>
                    </tr>
                    <tr>
                        <td>Votos positivos: </td>
                        <td>{{ contenido.votos_positivos }}</td>
                    </tr>
                    <tr>
                        <td>Votos negativos: </td>
                        <td>{{ contenido.votos_negativos }}</td>
                    </tr>
                    <tr>
                        <td>Fecha de publicación: </td>
                        <td>{{ contenido.fecha }}</td>
                    </tr>
                    <tr>
                        <td>Publicado por: </td>
                        <td>{{ contenido.usuario }}</td>
                    </tr>
                    <tr>
                        <td>Número de comentarios: </td>
                        <td>{{ contenido.Num_comentarios }}</td>
                    </tr>
                </table>
        {% endifequal %}
    {% endfor %}
<br>
{% else %}
<p> No existen contenidos aún </p>
{% endif %}

<H3 align="center">Tus comentarios </H3>
{% for comentario in lista_comentarios %}
    {% ifequal comentario.usuario request.user.username %}
<br>
        <table style="width:auto" align="center">
            <tr>
                <td><b> Título comentario: </b></td>
                <td>{{ comentario.titulo }}</td>
            </tr>
            <tr>
                <td><b> Título de la noticia: </b></td>
                <td>
                    <a href="/LoVisto/{{ comentario.contenido.titulo_noticia }}">{{ comentario.contenido.titulo_noticia }}</a>
                </td>
            </tr>
            <tr>
                <td><b> Url de la noticia: </b></td>
                <td>
                    <a href="{{ comentario.contenido.url_noticia }}">{{ comentario.contenido.url_noticia }}</a>
                </td>
            </tr>
            {% if comentario.url %}
            <tr>
                <td><b>Imagen:</b></td>
                <td><img src={{comentario.url}} align="center" width="300"></td>
            </tr>
            {% endif %}
            <tr>
                <td><b> Comentario: </b></td>
                <td>
                    <a>{{ comentario.descripcion }}</a>
                </td>
            </tr>
            <tr>
                <td><b> Fecha: </b></td>
                <td>{{ comentario.fecha }}</td>
            </tr>
        </table>

    {% endifequal %}
{% endfor %}
{% endblock %}

{% block lateral %}
<H3 align="center">Tus votos </H3>
<br>
{% for voto in lista_votos %}
    {% ifequal voto.usuario request.user.username %}
        <table style="width:auto" align="center">
            <tr>
                <td><b>Tipo de voto :</b></td>
                <td>{{ voto.valor }}</td>
            </tr>
            <tr>
                <td><b>Noticia votada:</b></td>
                <td>
                    <a href="/LoVisto/{{ voto.contenido.titulo_noticia }}">{{ voto.contenido.titulo_noticia }}</a>
                </td>
            </tr>
        </table>
    {%endifequal%}
<br>
{%endfor%}

<br>
<p><a href="https://www.urjc.es/">Pagina URJC</a></p>
            <iframe src="https://www.urjc.es/" height="400" width="65%" name="demo">
             <p>Necesita iframes para poder observar la previsualización</p>
            </iframe>
{% endblock %}

LoVisto/LoVisto/templates/LoVisto/pagina_wiki.html
{% extends 'LoVisto/pagina_recurso.html' %}
{% block aportacion %}
<div class="wikipedia">
  <p>Artículo Wikipedia: {{title}}</p>
  <img src={{imagen}} align="right">
  <p>Texto: {{txt}}
  <br>El texto está disponible bajo la Licencia Creative Commons Atribución Compartir Igual 3.0; pueden aplicarse cláusulas adicionales.
  <br>Al usar este sitio, usted acepta nuestros términos de uso y nuestra política de privacidad.
  <br>Wikipedia® es una marca registrada de la Fundación Wikimedia, Inc., una organización sin ánimo de lucro.
  <p><a href={{contenido.url_noticia}}> Url wikipedia</a></p>
</div>
{%endblock%}